#!/bin/bash

clear

HOOK_EXT="jhook"

BLACK='\e[0;30m'       # Black - Regular
RED='\e[0;31m'         # Red
GREEN='\e[0;32m'       # Green
YELLOW='\e[0;33m'      # Yellow
BLUE='\e[0;34m'        # Blue
PURPLE='\e[0;35m'      # Purple
CYAN='\e[0;36m'        # Cyan
WHITE='\e[0;37m'       # White
BOLD_BLACK='\e[1;30m'  # Black - Bold
BOLD_RED='\e[1;31m'    # Red
BOLD_GREEN='\e[1;32m'  # Green
BOLD_YELLOW='\e[1;33m' # Yellow
BOLD_GREEN='\e[1;34m'  # Blue
BOLD_PURPLE='\e[1;35m' # Purple
BOLD_CYAN='\e[1;36m'   # Cyan
BOLD_WHITE='\e[1;37m'  # White

unkblk='\e[4;30m' # Black - Underline
undred='\e[4;31m' # Red
undgrn='\e[4;32m' # Green
undylw='\e[4;33m' # Yellow
undblu='\e[4;34m' # Blue
undpur='\e[4;35m' # Purple
undcyn='\e[4;36m' # Cyan
undwht='\e[4;37m' # White
bakblk='\e[40m'   # Black - Background
bakred='\e[41m'   # Red
bakgrn='\e[42m'   # Green
bakylw='\e[43m'   # Yellow
bakblu='\e[44m'   # Blue
bakpur='\e[45m'   # Purple
bakcyn='\e[46m'   # Cyan
bakwht='\e[47m'   # White
txtrst='\e[0m'    # Text Reset

#Cagla

if [ -z $1 ]; then

    echo "Help"

else

	# git push
    if [ $1 == "push" ]; then

    	if [ $2 == "auto" ]; then

    		while true; do
    			diff_files=$( git diff --name-only )
    			short_stat=$( git diff --shortstat )

    			commit_message=$diff_files

    			if [ "$commit_message" != "" ]; then
    			
    				echo "Commit Message"
    				echo "$commit_message : $short_stat"
    				echo ""

    				git pull origin master
	    			git add .
	    			git commit -m "$commit_message"
	    			git push origin master
	    		
			        if [ -f ./push.after.$HOOK_EXT ]; then
	        			./push.after.$HOOK_EXT
	        		fi
	        	else
	        		echo "No change !"
    			fi

        		sleep 1
        		clear
    		done

    	else
			git pull origin master
	        git add .
	        git commit -m "$2"
	        git push origin master

	        if [ -f ./push.after.$HOOK_EXT ]; then
    			./push.after.$HOOK_EXT
    		fi
    	fi

    # git pull
    elif [ $1 == "pull" ]; then

        git pull origin master


    # git update base/master
    elif [ $1 == "update" ]; then

        if [ $2 == "base" ]; then
			git pull base master
        	git push origin master
        fi


    # Generate SSH Key
    elif [ $1 == "generate" ]; then

		if [ $2 == 'ssh-key' ]; then
			ssh-keygen -t rsa
    	    cat ~/.ssh/id_rsa.pub
		fi

    # Get SSH Key
    elif [ $1 == "get" ]; then

		if [ $2 == "ssh-key" ]; then
			cat ~/.ssh/id_rsa.pub
		fi

    # Apache Server
    elif [ $1 == "apache" ]; then


    	# Create New Site
		# jet apache create-site [DOMAIN] [PATH]
    	if [ $2 == "create-site" ]; then
    		
    		touch /etc/apache2/sites-available/$1.conf

			echo "<VirtualHost *:80>

			    ServerName $3

				ServerAdmin mustafa@aydemir.im
				DocumentRoot $4

			    <Directory \"$4\">
			        Require all granted
				AllowOverride All
			    </Directory>

				ErrorLog ${APACHE_LOG_DIR}/error.log
				CustomLog ${APACHE_LOG_DIR}/access.log combined

			</VirtualHost>" > /etc/apache2/sites-available/$3.conf

			mkdir $4
			chmod -R 755 $4
			touch $4/index.html
			echo "Hello World !" > $4/index.html

			a2ensite $3.conf
			service apache2 restart


		# Restart Server
		elif [ $2 == "restart" ]; then

			service apache2 restart

    	fi

    fi

fi
