#!/bin/bash

clear

HOOK_EXT="jhook"

CX_USR_SHARE_PATH="/usr/local/share/criexe"
USR_SHARE_PATH="/usr/local/share/criexe/jet"
HELP_URL="http://criexe.com/jet/help.txt"

ENDCOLOR='\033[0m'

RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'

LRED='\033[01;31m'
LGREEN='\033[01;32m'
LYELLOW='\033[01;33m'
LBLUE='\033[01;34m'
LPURPLE='\033[01;35m'
LCYAN='\033[01;36m'
WHITE='\033[01;37m'

if [ -z $1 ]; then

	# Not Installed !
	if [ ! -d "$USR_SHARE_PATH" ]; then
		echo -e "${RED}JET is not installed !${ENDCOLOR}"
		echo -e "${YELLOW}Installing...${ENDCOLOR}"
		echo -e ""

		mkdir "$CX_USR_SHARE_PATH"
		mkdir "$USR_SHARE_PATH"
		chmod -R 777 $USR_SHARE_PATH
		curl -o "$USR_SHARE_PATH/help.txt" $HELP_URL
		clear
		cat "$USR_SHARE_PATH/help.txt"
	else
		clear
		cat "$USR_SHARE_PATH/help.txt"
	fi

else

	# git push
    if [ $1 == "push" ]; then
 
		if [ -n $2 ]; then
			if [ $2 == "auto" ]; then

				while true; do
					diff_files=$( git diff --name-only )
					short_stat=$( git diff --shortstat )

					commit_message=$diff_files

					if [ "$commit_message" != "" ]; then
					
						echo -e "${GREEN}Commit Message${ENDCOLOR}"
						echo -e "${YELLOW}$commit_message :${ENDCOLOR} $short_stat"
						echo ""

						git pull origin master
						git add .
						git commit -m "$commit_message"
						git push origin master
					
						if [ -f ./push.after.$HOOK_EXT ]; then
							./push.after.$HOOK_EXT
						fi
					else
						echo "No change ! \r"
					fi

					sleep 1
					clear
				done

			else

				git pull origin master
				git add .
				git commit -m "$2"
				git push origin master

				if [ -f ./push.after.$HOOK_EXT ]; then
					./push.after.$HOOK_EXT
				fi
			fi
		fi

		

    # git pull
    elif [ $1 == "pull" ]; then

        git pull origin master


    # git update base/master
    elif [ $1 == "update" ]; then

		if [ -n $2 ]; then
			 if [ -n $2 && $2 == "base" ]; then
				git pull base master
				git push origin master
			fi		
		fi # $2 is not null


    # Generate SSH Key
    elif [ $1 == "generate" ]; then

		if [ -n $2 && $2 == 'ssh-key' ]; then
			ssh-keygen -t rsa
    	    cat ~/.ssh/id_rsa.pub
		fi

    # Get SSH Key
    elif [ $1 == "get" ]; then

		if [ -n $2 ]; then
			if [ $2 == "ssh-key" ]; then
				cat ~/.ssh/id_rsa.pub
			fi
		fi # $2 is not null

    # Apache Server
    elif [ $1 == "apache" ]; then

    	if [ -n $2 ]; then
			# Create New Site
			# jet apache create-site [DOMAIN] [PATH]
			if [ $2 == "create-site" ]; then
				
				touch /etc/apache2/sites-available/$1.conf

				echo "<VirtualHost *:80>

					ServerName $3

					ServerAdmin mustafa@aydemir.im
					DocumentRoot $4

					<Directory \"$4\">
						Require all granted
					AllowOverride All
					</Directory>

					ErrorLog ${APACHE_LOG_DIR}/error.log
					CustomLog ${APACHE_LOG_DIR}/access.log combined

				</VirtualHost>" > /etc/apache2/sites-available/$3.conf

				mkdir $4
				chmod -R 755 $4
				touch $4/index.html
				echo "Hello World !" > $4/index.html

				a2ensite $3.conf
				service apache2 restart


			# Restart Server
			elif [ $2 == "restart" ]; then
				service apache2 restart
			fi

		fi # $2 is not null
    fi

fi
