#!/bin/bash

# Author        : Mustafa Aydemir (mustafa@aydemir.im)
# Latest Update : July 18, 2017
# Version       : v0.10

HOOK_EXT="jhook"

CX_USR_SHARE_PATH="/usr/local/share/criexe"
USR_SHARE_PATH="/usr/local/share/criexe/jet"
HELP_URL="http://criexe.com/jet/latest/help.txt"

CX_TMP_PATH="/tmp/criexe"
TMP_PATH="/tmp/criexe/jet"
UPDATE_URL="http://criexe.com/jet/latest/source.txt"

ENDCOLOR='\033[0m'

RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'

LRED='\033[01;31m'
LGREEN='\033[01;32m'
LYELLOW='\033[01;33m'
LBLUE='\033[01;34m'
LPURPLE='\033[01;35m'
LCYAN='\033[01;36m'
WHITE='\033[01;37m'

if [ -z $1 ]; then

	# Not Installed !
	if [ ! -d "$USR_SHARE_PATH" ]; then
		echo -e "${RED}JET is not installed !${ENDCOLOR}"
		echo -e "${YELLOW}Installing...${ENDCOLOR}"
		echo -e ""

		mkdir "$CX_USR_SHARE_PATH"
		mkdir "$USR_SHARE_PATH"
		chmod -R 777 $USR_SHARE_PATH
		curl -o "$USR_SHARE_PATH/help.txt" $HELP_URL
		clear
		cat "$USR_SHARE_PATH/help.txt"
	else
		clear
		cat "$USR_SHARE_PATH/help.txt"
	fi

else

	# git push
    if [ $1 == "push" ]; then
 
		if [ -n $2 ]; then
			if [ $2 == "auto" ]; then

				while true; do
					diff_files=$( git diff --name-only )
					short_stat=$( git diff --shortstat )

					commit_message=$diff_files

					if [ "$commit_message" != "" ]; then
					
						echo -e "${GREEN}Commit Message${GREEN}"
						echo -e "${YELLOW}$commit_message :${ENDCOLOR} $short_stat"
						echo ""

						echo -e "${YELLOW}Pulling...${ENDCOLOR}"
						git pull origin master
						echo -e "${YELLOW}Committing...${ENDCOLOR}"
						git add .
						git commit -m "$commit_message"
						echo -e "${YELLOW}Pushing...${ENDCOLOR}"
						git push origin master
						echo -e "${GREEN}Success !${ENDCOLOR}"
						
						if [ -f ./push.after.$HOOK_EXT ]; then
							./push.after.$HOOK_EXT
						fi
					else
						echo -e "${RED}No change !${ENDCOLOR}"
					fi

					sleep 1
					clear
				done

			else

				echo -e "${YELLOW}Pulling...${ENDCOLOR}"
				git pull origin master
				echo -e "${YELLOW}Committing...${ENDCOLOR}"
				git add .
				git commit -m "$2"
				echo -e "${YELLOW}Pushing...${ENDCOLOR}"
				git push origin master
				echo -e "${GREEN}Success !${ENDCOLOR}"

				if [ -f ./push.after.$HOOK_EXT ]; then
					./push.after.$HOOK_EXT
				fi
			fi
		fi

		

    # git pull
    elif [ $1 == "pull" ]; then

		echo -e "${YELLOW}Pulling...${ENDCOLOR}"
        git pull origin master


    # git update base/master
    elif [ $1 == "update" ]; then

		if [ $# -eq 2 ]; then
			 if [ $2 == "base" ]; then
			 	echo -e "${YELLOW}Updating :${ENDCOLOR} base/master"
				git pull base master
				git push origin master
			fi		
		else
			# Update JET
			echo -e "${YELLOW}Updating :${ENDCOLOR} JET"
			mkdir $CX_TMP_PATH
			mkdir $TMP_PATH
			chmod -R 777 $TMP_PATH
			curl -o "$TMP_PATH/jet" $UPDATE_URL
			mv "$TMP_PATH/jet" /usr/local/bin/jet
			chmod 755 /usr/local/bin/jet
			jet
		fi 


    # Generate SSH Key
    elif [ $1 == "generate" ]; then

		if [ -n $2 && $2 == 'ssh-key' ]; then
			ssh-keygen -t rsa
    	    cat ~/.ssh/id_rsa.pub
		fi

    # Get SSH Key
    elif [ $1 == "get" ]; then

		if [ -n $2 ]; then
			if [ $2 == "ssh-key" ]; then
				cat ~/.ssh/id_rsa.pub
			fi
		fi # $2 is not null

    # Apache Server
    elif [ $1 == "apache" ]; then

    	if [ -n $2 ]; then
			# Create New Site
			# jet apache create-site [DOMAIN] [PATH]
			if [ $2 == "create-site" ]; then
				
				touch /etc/apache2/sites-available/$1.conf

				echo "<VirtualHost *:80>

					ServerName $3

					ServerAdmin mustafa@aydemir.im
					DocumentRoot $4

					<Directory \"$4\">
						Require all granted
					AllowOverride All
					</Directory>

					ErrorLog ${APACHE_LOG_DIR}/error.log
					CustomLog ${APACHE_LOG_DIR}/access.log combined

				</VirtualHost>" > /etc/apache2/sites-available/$3.conf

				mkdir $4
				chmod -R 755 $4
				touch $4/index.html
				echo "Hello World !" > $4/index.html

				a2ensite $3.conf
				service apache2 restart


			# Restart Server
			elif [ $2 == "restart" ]; then
				service apache2 restart
			fi

		fi # $2 is not null
    fi

fi
